### ISSUE TITLE
Implement 'plain' selectors (not strings)

### ISSUE THREAD

**Issue by alerque** [alerque/handlebars-helper-fluent#2]
```hbs
{{fluent foo}}
{{fluent foo.bar}}
```

This might be tricky to _imlement_ in Javascript but it makes sense from the standpoint of the other languages being made into templates. Optionally also support the current string based key syntax.

See [discussion on Discord](https://discourse.mozilla.org/t/handlebars-helper-for-i18n-of-templates-using-fluent/44980/6?u=alerque) about matching @Manishearth's Rust helper implementation.

**Comment by alerque** [comment]
Hey @Manishearth I had a look around at some Handlebars helpers in Javascript and can't find a single one that allows an argument to be passed to the helper as a string without quoting it. In fact inspecting what gets passed to my `helper()` used in `registerHelper('fluent, helper)`, its argument(s) end up as `undefined`.

It seems like the Javascript implementation of Handlebars can only accept:

* A number, e.g. `{{helper 17}}`
* A string, e.g. `{{helper "foo"}}`
* A reference , e.g. `{{helper foo}}` where `foo` is a valid key to to something in the Javascript context object at runtime.

I can simulate the results by setting `var context = { key: "key" };` before calling the helper as `Handlebars.compile("{{fluent key}}")(context)`. In that event the helper gets passes a string `"key"`, but that's because there was a lookup for it in the context object.

I don't see any way for the helper to change this behavior, for example by injecting key→key maps into the data array. That can be done, but it has to be done when running `Handlebars.compile()`, it can't seem to be done when registering a helper.

If there is a single other helper out that that has figured out how to eschew the variable lookup step and just pass themselves the argument as a string I would be happy to implement this.

**Comment by Manishearth** [comment]
Yeah, sounds like we've made a mistake here, the bare paths are for variable references.

I'm not currently working on this stuff but whenever I split the handebars thing out I'll try and fix this as well.

**Comment by Manishearth** [comment]
(feel free to close this)

**Comment by alerque** [comment]
I've been toying with this in my head, and in seems like we _could_ make it work. What we'd have to do is inject all the possible translations as variable into the environment before we got started. Basically we'd have to patch into the `register()` function and inject a bunch of globals, or stash something inside the Handlebars class.

That kind of hackery sounds dirty to me and clearly isn't the way Handlebars was designed. I'd be happy to review this decision if anybody has a case to make for why that would be a good thing — but for now I think we should stick to the standard paradigm here and the Rust implementation should be fixed to be more standard Handlebars syntax.

**Comment by Manishearth** [comment]
btw @alerque I've started work on the helper [here](https://github.com/manishearth/handlebars-fluent). It follows the same syntax as this one.

**Comment by Manishearth** [comment]
The helper is now "complete", it has tests and documentation and seems to work. I'll let others start using it before releasing a 1.0.

**Comment by alerque** [comment]
Thanks for the status update @Manishearth. I have one or two applications that I'll probably port to using your Rust implementation eventually, but the next time I'll work on those is probably as far out as February. Hopefully somebody else gives it a shake down before I do!
